theme: jekyll-theme-hacker 
title: feifan's daily murmurs
author: ftppz
description: Just for fun.

remote_theme: pages-themes/hacker@v0.2.0
plugins: 
  - jekyll-remote-theme


markdown: kramdown
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
